[ui.anchors]
top = true
left = true
right = true
bottom = true

[ui.window]
h_align = "fill"
v_align = "fill"

[ui.window.box]
h_align = "center"
width = 520               # compact but not cramped

[ui.window.box.margins]
top = 24                  # near-top like rofi oneline

[ui.window.box.bar]
orientation = "horizontal"
position = "end"

[ui.window.box.bar.entry]
h_align = "fill"
h_expand = true

[ui.window.box.bar.entry.icon]
h_align = "center"
h_expand = true
pixel_size = 18
theme = ""

[ui.window.box.search.prompt]
name = "prompt"
icon = "edit-find"
pixel_size = 18
h_align = "center"
v_align = "center"

[ui.window.box.search.clear]
name = "clear"
icon = "edit-clear"
pixel_size = 18
h_align = "center"
v_align = "center"

[ui.window.box.search.input]
h_align = "fill"
h_expand = true
icons = true

[ui.window.box.search.spinner]
hide = true

[ui.window.box.scroll.list]
max_height = 360
max_width = 520
min_width = 520
width = 520
marker_color = "#005f87"     # rofi maincolor

[ui.window.box.scroll.list.margins]
top = 8

[ui.window.box.scroll.list.item.icon]
pixel_size = 22
theme = ""

[ui.window.box.scroll.list.item.activation_label]
width = 16
x_align = 0.5
y_align = 0.5

