[pyprland]
plugins = [
  "fetch_client_menu",
  "scratchpads",
  "toggle_special",
  "wallpapers",
]

[wallpapers]
unique = true # set a different wallpaper for each screen
path = "~/pic/wl"
interval = 60 # change every hour
extensions = ["jpg", "jpeg", ".png", ".webp"]
recurse = true
command = 'swww img --transition-type any "[file]"'
clear_command = "swww clear"

[scratchpads.im]
animation = "fromRight"
command = "QT_QPA_PLATFORMTHEME=gtk3 telegram-desktop"
class = "org.telegram.desktop"
size = "30% 90%"
lazy = false

[scratchpads.discord]
animation = "fromRight"
command = "vesktop"
class = "vesktop"
size = "50% 40%"
lazy = true

[scratchpads.music]
animation = ""
command = "kitty --class music -e ncmpcpp"
margin = "80%"
class = "music"
position = "15% 50%"
size = "70% 40%"
lazy = false
unfocus = "hide"

[scratchpads.torrment]
animation = ""
command = "kitty --class torrment -e rustmission"
class = "torrment"
position = "1% 0%"
size = "98% 40%"
lazy = false
unfocus = "hide"

[scratchpads.teardown]
animation = ""
command = "kitty --class teardown -e btop"
class = "teardown"
position = "1% 0%"
size = "98% 50%"
lazy = false

[scratchpads.mixer]
animation = "fromRight"
command = "pwvucontrol"
class = "com.saivert.pwvucontrol"
lazy = true
size = "40% 90%"
unfocus = "hide"
