[pyprland]
plugins = [
  "scratchpads",
  "fetch_client_menu",
]

[scratchpads.teardown]
animation = "fromTop"
command = "kitty --class teardown -e btop"
class = "teardown"
size = "90% 60%"

[scratchpads.volume]
animation = "fromRight"
command = "pwvucontrol"
class = "com.saivert.pwvucontrol"
lazy = true
size = "40% 90%"
unfocus = "hide"
