# Ashell log level filter, possible values "debug" | "info" | "warn" | "error". Needs reload
log_level = "warn"
outputs = "All"
position = "Bottom"
app_launcher_cmd = "~/.config/rofi/launcher.sh"
clipboard_cmd = "cliphist-rofi-img | wl-copy"
truncate_title_after_length = 150

[modules]
left = [ "Workspaces" ]
right = [ "SystemInfo", [ "Clock", "Privacy", "Settings" ], "CustomNotifications" ]

[updates]
check_cmd = "checkupdates; paru -Qua"
update_cmd = 'alacritty -e bash -c "paru; echo Done - Press enter to exit; read" &'

[workspaces]
visibility_mode = "All"
enable_workspace_filling = false

[keyboard_layout.labels]
"English (US)" = "🇺🇸"
"Russian" = "🇷🇺"

[system]
indicators = [ "Cpu", "Memory", "Temperature" ]

[system.cpu]
warn_threshold = 60
alert_threshold = 80

[system.memory]
warn_threshold = 70
alert_threshold = 85

[system.temperature]
warn_threshold = 60
alert_threshold = 80

[system.disk]
warn_threshold = 80
alert_threshold = 90

[clock]
format = "%a %d %b %R"

[media_player]
max_title_length = 100

[[CustomModule]]
name = "CustomNotifications"
icon = ""
command = "swaync-client -t -sw"
listen_cmd = "swaync-client -swb"
icons.'dnd.*' = ""
alert = ".*notification"

[settings]
lock_cmd = "hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"

[appearance]
# Увеличиваем шрифт и меняем на Iosevka
font_name = "Iosevka 12"
opacity = 0.7

# Холодная цветовая схема Mirodark
background_color = "#1a1e24"
primary_color = "#6cb6eb"  # Основной акцент (синий)
secondary_color = "#141a20"  # Тёмный фон
success_color = "#8fbcbb"  # Зеленовато-голубой
danger_color = "#e78284"  # Тёплый красный (контрастный)
text_color = "#c6d0f5"  # Светлый текст

# Цвета рабочих пространств (холодные оттенки)
workspace_colors = [ "#6cb6eb", "#8fbcbb", "#81c1e1" ]
special_workspace_colors = [ "#a6d189", "#e78284" ]

[appearance.menu]
opacity = 0.7
backdrop = 0.3
