# Build options
[buildOptions]
optimizeWithTtx = false

[buildPlans.iosevka-neg]
    family = "Iosevka"
    desc = "Default"
    calt = false
    export-glyph-names = true
    webfont-formats = ['ttf']
    spacing = "fontconfig-mono"
    snapshotFamily = 'iosevka'
    snapshotFeature = '"NWID" off'
[buildPlans.iosevka-neg.ligations]
    inherits = "dlig"
    brace-bar = false
    brack-bar = false
    connected-tilde-as-wave = false
    connected-hyphen-as-solid-line = false
    connected-hyphen-as-semi-dashed-line = false
[buildPlans.iosevka-neg.variants.design]
    capital-a = 'straight-top-serifed'
    capital-b = 'standard-unilateral-serifed'
    capital-c = 'unilateral-inward-serifed'
    capital-d = 'standard-bilateral-serifed'
    capital-e = 'top-left-serifed'
    capital-f = 'top-left-serifed'
    capital-g = 'toothed-serifed-hooked'
    capital-h = 'top-left-serifed'
    capital-i = 'short-serifed'
    capital-j = 'serifed-both-sides'
    capital-k = 'straight-bottom-right-serifed'
    capital-l = 'motion-serifed'
    capital-m = 'hanging-motion-serifed'
    capital-n = 'standard-motion-serifed'
    capital-p = 'closed-motion-serifed'
    capital-q = 'crossing-curly-tailed'
    capital-r = 'straight-open-serifed'
    capital-s = 'unilateral-inward-serifed'
    capital-t = 'serifless'
    capital-u = 'toothed-serifless'
    capital-v = 'straight-motion-serifed'
    capital-w = 'straight-motion-serifed'
    capital-x = 'straight-motion-serifed'
    capital-y = 'curly-serifless'
    capital-z = 'curly-serifed'
    capital-delta = 'curly'
    a = 'double-storey-tailed'
    b = 'toothed-serifless'
    c = 'serifless'
    d = 'toothed-serifed'
    e = 'flat-crossbar'
    f = 'flat-hook-tailed'
    g = 'double-storey'
    h = 'tailed-serifed'
    i = 'serifed-flat-tailed'
    j = 'serifed'
    k = 'symmetric-touching-top-left-serifed'
    l = 'serifed-semi-tailed'
    m = 'tailed-top-left-serifed'
    n = 'straight-serifless'
    p = 'eared-serifless'
    q = 'straight-serifless'
    r = 'corner-hooked-serifless'
    s = 'bilateral-inward-serifed'
    t = 'bent-hook'
    u = 'toothed-serifless'
    v = 'curly-motion-serifed'
    w = 'straight-motion-serifed'
    x = 'curly-motion-serifed'
    y = 'curly-turn-motion-serifed'
    z = 'curly-serifed'
    lower-alpha = 'crossing'
    capital-gamma = 'serifed'
    lower-delta = 'rounded'
    lower-lambda = 'curly-turn'
    lower-mu = 'tailed-serifless'
    lower-xi = 'flat-top'
    cyrl-capital-ze = 'bilateral-inward-serifed'
    cyrl-ze = 'serifless'
    cyrl-capital-ka = 'curly-serifless'
    cyrl-ka = 'curly-serifless'
    cyrl-el = 'straight'
    cyrl-ef = 'top-serifed'
    cyrl-che = 'standard'
    cyrl-capital-ya = 'curly-serifless'
    cyrl-ya = 'curly-serifless'
    zero = 'slashed'
    one = 'base-long-top-serif'
    two = 'curly-neck'
    three = 'flat-top'
    four = 'semi-open'
    five = 'oblique-arched'
    six = 'closed-contour'
    seven = 'curly-serifed'
    eight = 'crossing'
    nine = 'open-contour'
    punctuation-dot = 'round'
    tilde = 'low'
    asterisk = 'turn-hex-low'
    underscore = 'low'
    caret = 'low'
    ascii-grave = 'straight'
    ascii-single-quote = 'straight'
    paren = 'flat-arc'
    brace = 'straight'
    number-sign = 'upright'
    ampersand = 'closed'
    at = 'fourfold'
    dollar = 'interrupted'
    cent = 'bar-interrupted'
    percent = 'rings-segmented-slash'
    bar = 'force-upright'
    question = 'corner'
    lig-ltgteq = 'slanted'
    # lig-plus-chain = 'with-notch'

[collectPlans.iosevka-neg]
release = true
from = [
	"iosevka-neg",
]

[weights.thin]
shape = 100
menu  = 100
css   = 100

[weights.extralight]
shape = 200
menu  = 200
css   = 200

[weights.light]
shape = 300
menu  = 300
css   = 300

[weights.regular]
shape = 400
menu  = 400
css   = 400

[weights.medium]
shape = 500
menu  = 500
css   = 500

[weights.semibold]
shape = 600
menu  = 600
css   = 600

[weights.bold]
shape = 700
menu  = 700
css   = 700

[weights.extrabold]
shape = 800
menu  = 800
css   = 800

[weights.heavy]
shape = 900
menu  = 900
css   = 900

# slope mappings (style => slope angle, shape slope grade, menu slope, CSS slope)
[slopes.upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[slopes.oblique]
angle = 9.4
shape = "oblique"
menu  = "oblique"
css   = "oblique"

[slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

[widths.normal]
shape = 500
menu  = 5
css   = "normal"

[widths.extended]
shape = 600
menu  = 7
css   = "expanded"
