# Unified formatter config for this flake

[global]
# Keep noise down and avoid rewriting encrypted or VCS-managed files
excludes = [
  "flake.lock",
  ".git/*",
  "secrets/crypted/*",
  "shell/.config/tmux/plugins/tpm/**",
]

# Nix files: format with alejandra
[formatter.nix]
command = "alejandra"
options = ["-q"]
includes = ["*.nix"]

# Remove unused attributes from Nix files in-place
[formatter.deadnix]
command = "deadnix"
options = ["--edit"]
includes = ["*.nix"]

# Static analysis and auto-fixes where possible
[formatter.statix]
command = "statix"
options = ["fix"]
includes = ["*.nix"]

# Shell: format POSIX/Bash scripts (exclude zsh)
[formatter.shfmt]
command = "shfmt"
options = ["-w", "-i", "2", "-ci", "-bn", "-sr"]
includes = ["**/*.sh", "**/*.bash"]

[formatter.shellcheck]
command = "shellcheck"
options = ["-S", "style", "-x"]
includes = ["**/*.sh", "**/*.bash"]

# Python: auto-fix with ruff, then format with black
[formatter.ruff]
command = "ruff"
options = ["--fix"]
includes = ["**/*.py"]

[formatter.black]
command = "black"
options = ["--quiet", "--line-length", "100"]
includes = ["**/*.py"]
